#
# This is only for development on a local computer!!!
#
frontend:
  build: frontend
  environment:
    - DEBUG=${DEBUG}
  ports:
    - 9000:80
  volumes:
    - ./frontend/app:/app
    - ${DATADIR}:/data
  links:
    - backend
    - elasticsearch
  log_opt:
    max-size: "1m"
    max-file: "2"

backend:
  build: backend
  env_file: .env
  environment:
    - DEBUG=${DEBUG}
    - WORKER_COUNT=6
    # - LDAP_USERNAME=${LDAP_USERNAME}
    # - LDAP_PASSWORD=${LDAP_PASSWORD}
    # - LDAP_SERVER=${LDAP_SERVER}
    # - LDAP_BASE_DN=${LDAP_BASE_DN}
  expose:
    - 5000
  volumes:
    - ./backend:/app
    - ${DATADIR}:/data
  links:
    - elasticsearch
    - redis
  log_opt:
    max-size: "1m"
    max-file: "2"
  command:
    - server

worker:
  build: backend
  env_file: .env
  environment:
    - DEBUG_=${DEBUG}
    - WORKER_COUNT=3
    # - LDAP_USERNAME=${LDAP_USERNAME}
    # - LDAP_PASSWORD=${LDAP_PASSWORD}
    # - LDAP_SERVER=${LDAP_SERVER}
    # - LDAP_BASE_DN=${LDAP_BASE_DN}
  volumes:
    - ./backend:/app
    - ${DATADIR}:/data
  links:
    - redis
    - elasticsearch
  log_opt:
    max-size: "1m"
    max-file: "2"
  command:
    - worker

elasticsearch:
  image: elasticsearch:5.2.1
  environment:
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"
  ports:
    - 9200:9200
    - 9300:9300
  volumes:
    - ./tmp/esdata:/usr/share/elasticsearch/data
  log_opt:
    max-size: "1m"
    max-file: "2"

redis:
  image: redis:alpine
  log_opt:
    max-size: "1m"
    max-file: "2"
